export let charts = [
  { char: "A", id: "a1" },
  { char: "B", id: "a2" },
  { char: "C", id: "a3" },
  { char: "D", id: "a4" },
  { char: "E", id: "a5" },
  { char: "F", id: "a6" },
  { char: "G", id: "a7" },
  { char: "H", id: "a8" },
  { char: "I", id: "a9" },
  { char: "J", id: "a10" },
  { char: "K", id: "a11" },
  { char: "L", id: "a12" },
  { char: "M", id: "a13" },
  { char: "N", id: "a14" },
  { char: "O", id: "a15" },
  { char: "P", id: "a16" },
  { char: "Q", id: "a17" },
  { char: "R", id: "a18" },
  { char: "S", id: "a19" },
  { char: "T", id: "a20" },
  { char: "U", id: "a21" },
  { char: "V", id: "a22" },
  { char: "W", id: "a23" },
  { char: "X", id: "a24" },
  { char: "Y", id: "a25" },
  { char: "Z", id: "a26" },
];
