export let categories = [
  "pizza",
  "frensh salad",
  "green burger",
  "hourse",
  "lion",
  "elephant",
  "doctor",
  "developer",
  "taxi driver",
  "dog",
  "carmen",
  "marwan",
  "soso",
  "tanta",
  "manal",
  "nour",
  "ahmed",
  "yara",
  "reham",
  "adm",
  "alexandria",
  "china",
  "foot ball",
  "hooky",
  "hand ball",
  "cairo",
  "dubai",
  "ghaza",
  "canada",
  "barcelona",
];

export let ctg = [
  { ctg: "food", items: ["pizza", "frensh salad", "green burger"] },
  { ctg: "animals", items: ["hourse", "lion", "elephant"] },
  { ctg: "jobs", items: ["doctor", "developer", "taxi driver"] },
  {
    ctg: "names",
    items: [
      "carmen",
      "marwan",
      "soso",
      "manal",
      "nour",
      "ahmed",
      "yara",
      "reham",
      "adm",
    ],
  },
  {
    ctg: "countries",
    items: [
      "tanta",
      "alexandria",
      "cairo",
      "dubai",
      "ghaza",
      "canada",
      "barcelona",
    ],
  },
  { ctg: "sports", items: ["football", "hooky", "handball", "swimming"] },
];
